# Generated by Django 2.2.1 on 2019-05-09 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Charges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breakage_charges', models.FloatField()),
                ('laundry_charges', models.FloatField()),
                ('lost_key_charges', models.FloatField()),
                ('guest_charges', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Other_Charges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_name', models.CharField(max_length=50)),
                ('charge_value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('id_no', models.CharField(max_length=20)),
                ('room_no', models.IntegerField()),
                ('joining_date', models.DateField()),
                ('leaving_date', models.DateField()),
                ('block', models.CharField(max_length=1)),
                ('mob_no', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('date_added', models.DateTimeField()),
                ('charges', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Charges')),
            ],
        ),
        migrations.AddField(
            model_name='charges',
            name='other_charges',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Other_Charges'),
        ),
    ]
