# Generated by Django 2.2.1 on 2019-05-11 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='charges',
        ),
    ]
