# Generated by Django 2.2.1 on 2019-05-14 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_remove_student_charges'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='charges',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='students.Charges'),
        ),
        migrations.AlterField(
            model_name='charges',
            name='breakage_charges',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='charges',
            name='guest_charges',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='charges',
            name='laundry_charges',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='charges',
            name='lost_key_charges',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='other_charges',
            name='charge_value',
            field=models.FloatField(default=0),
        ),
    ]
