# Generated by Django 2.2.1 on 2019-06-18 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20190612_1200'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Guest',
        ),
    ]
