# Generated by Django 2.2.1 on 2019-06-18 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('PL', 'Placement'), ('INT', 'Internship'), ('OINT', 'Outside Internship'), ('OVS', 'Overstay'), ('BFR', 'Before Registration'), ('STM', 'Summer Term'), ('PS1', 'PS1'), ('PS2E', 'PS2 Early'), ('PS2L', 'PS2 Late'), ('PRO', 'Project'), ('SG', 'Student Guests'), ('WG', 'WILP Guests')], max_length=1)),
                ('room_no', models.IntegerField()),
                ('joining_date', models.DateField()),
                ('leaving_date', models.DateField()),
                ('mob_no', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('date_added', models.DateTimeField()),
                ('charges', models.FloatField(default=0)),
            ],
        ),
    ]
